-- tests/rng_spec.lua
--
-- Golden vectors below were generated by tests/golden/reference.c —
-- the algorithm authors' public-domain C plus Sonder's derivation
-- rule. If the Lua port and the C oracle agree bit-for-bit, a
-- transcription error would have to be mirrored in both to hide.
-- Hex literals ≥ 2^63 wrap to negative Lua integers; same bits.

local Rng = require "sonder.rng"

describe("splitmix64", function()
   it("matches the C reference from seed 1893", function()
      local expected = {
         0x448fba586c8b087b,
         0x5819e40663921cf5,
         0xd8c49e7870c01968,
         0x6f069040121b2e2c,
      }
      local s, out = 1893, nil
      for i = 1, 4 do
         s, out = Rng._splitmix64(s)
         assert.equal(expected[i], out)
      end
   end)
end)

describe("xoshiro256**", function()
   it("matches the C reference from state {1,2,3,4}", function()
      local expected = {
         0x0000000000002d00,
         0x0000000000000000,
         0x000000005a007080,
         0x10e0000000009d80,
         0x10e0b61ce1009d80,
      }
      local stream = Rng._stream_from_state(1, 2, 3, 4)
      for i = 1, 5 do
         assert.equal(expected[i], stream:next())
      end
   end)

   it("emits near-zero garbage from a naive state — why splitmix seeds it", function()
      -- The vector above is also the cautionary tale: from {1,2,3,4}
      -- the second draw is literally 0. xoshiro needs well-mixed state
      -- before its output looks random; splitmix64 provides it.
      local stream = Rng._stream_from_state(1, 2, 3, 4)
      stream:next()
      assert.equal(0, stream:next())
   end)

   it("escapes the all-zero fixed point", function()
      -- Unguarded, {0,0,0,0} maps to itself and every draw is 0
      -- forever. The guard can't make the *first* draw nonzero (the
      -- output function reads only one state word, still 0), but it
      -- must make the state escape rather than stick.
      local stream = Rng._stream_from_state(0, 0, 0, 0)
      local any_nonzero = false
      for _ = 1, 4 do
         any_nonzero = any_nonzero or stream:next() ~= 0
      end
      assert.is_true(any_nonzero)
   end)
end)

describe("stream derivation", function()
   it("hashes (seed, name) as the C reference does", function()
      assert.equal(0xfd959b6eb92bb149, Rng._stream_hash(1893, "market"))
      assert.equal(0x09a220205a65a62d, Rng._stream_hash(1893, "war"))
   end)

   it("expands to the reference's xoshiro state", function()
      local s0, s1, s2, s3 = Rng._stream_derive(1893, "market"):state()
      assert.equal(0xd339e512781132b7, s0)
      assert.equal(0xafe7febe36e1fc52, s1)
      assert.equal(0x4dcdc958cbe6067d, s2)
      assert.equal(0xf218642849ebf06a, s3)
   end)

   it("draws the reference's sequences for (1893, market) and (1893, war)", function()
      local market = {
         0xe3e3b7d2dcad36ef,
         0x3e0a7db280a1604a,
         0x4153f432d4206dd6,
         0xcf14f7eb37b82b5a,
         0x5d5179d375aaf432,
      }
      local war = {
         0x59d335440fc90574,
         0x674b682e8ff9ef72,
         0x5645aa019c62cf22,
         0x6b274e8ed27410a1,
         0x23b7a49f200b1ae6,
      }
      local rng = Rng.new(1893)
      for i = 1, 5 do
         assert.equal(market[i], rng:stream("market"):next())
         assert.equal(war[i], rng:stream("war"):next())
      end
   end)
end)

describe("named streams", function()
   it("returns the same stream object for the same name", function()
      local rng = Rng.new(7)
      assert.equal(rng:stream("market"), rng:stream("market"))
   end)

   it("gives different names different sequences", function()
      local rng = Rng.new(7)
      assert.not_equal(rng:stream("market"):next(), rng:stream("war"):next())
   end)

   it("draws identically across separately built universes", function()
      local a, b = Rng.new(424242), Rng.new(424242)
      for _ = 1, 100 do
         assert.equal(a:stream("market"):next(), b:stream("market"):next())
      end
   end)

   it("is unmoved by other streams existing or drawing (the law)", function()
      -- Universe A: the market alone. Universe B: a noisy new feature
      -- draws heavily from its own stream, interleaved. The market
      -- must not be able to tell.
      local a, b = Rng.new(99), Rng.new(99)
      for _ = 1, 50 do
         b:stream("comets"):next()
         b:stream("comets"):next()
         assert.equal(a:stream("market"):next(), b:stream("market"):next())
      end
   end)

   it("rejects non-integer seeds and invalid names", function()
      assert.has_error(function() Rng.new(1.5) end)
      assert.has_error(function() Rng.new("1893") end)
      local rng = Rng.new(1)
      assert.has_error(function() rng:stream("") end)
      assert.has_error(function() rng:stream(nil) end)
   end)
end)

describe("int(lo, hi)", function()
   it("stays in bounds and reaches every value in a small range", function()
      local stream = Rng._stream_derive(1893, "dice")
      local seen = {}
      for _ = 1, 200 do
         local v = stream:int(1, 6)
         assert.is_true(v >= 1 and v <= 6)
         seen[v] = true
      end
      for face = 1, 6 do
         assert.is_true(seen[face], "face " .. face .. " never rolled")
      end
   end)

   it("handles power-of-two spans with the mask alone", function()
      local stream = Rng._stream_derive(1893, "mask")
      for _ = 1, 100 do
         local v = stream:int(0, 7)
         assert.is_true(v >= 0 and v <= 7)
      end
   end)

   it("handles negative bounds", function()
      local stream = Rng._stream_derive(1893, "neg")
      for _ = 1, 100 do
         local v = stream:int(-3, 3)
         assert.is_true(v >= -3 and v <= 3)
      end
   end)

   it("handles a degenerate one-value range", function()
      local stream = Rng._stream_derive(1893, "one")
      assert.equal(42, stream:int(42, 42))
   end)

   it("survives the full integer range", function()
      local stream = Rng._stream_derive(1893, "full")
      assert.equal("integer", math.type(stream:int(math.mininteger, math.maxinteger)))
   end)

   it("rejects float bounds and empty ranges", function()
      local stream = Rng._stream_derive(1893, "bad")
      assert.has_error(function() stream:int(1.0, 6) end)
      assert.has_error(function() stream:int(6, 1) end)
   end)
end)
